AllCops:
  Exclude:
    - 'bin/console'
    - 'logstash-output-dynamodb.gemspec'
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Metrics/BlockLength:
  Max: 500

Metrics/LineLength:
  Max: 100

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Style/MultilineBlockChain:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned
